### ISSUE TITLE
Error: SerdeJsonError(Error("missing field `price`", line: 1, column: 949))

### ISSUE THREAD

**Issue by ethanwc** [goddtriffin/yelp-fusion-rs#2]
**Describe the bug**
When `price` info is missing json parsing fails.

**To reproduce**
1. Configure env / fusion key to work in example `business_search`
2. Modify payload like so:
```rust
    let business_search_payload: BusinessSearchPayload = BusinessSearchPayload::builder()
        .coordinates(Coordinates::new(50.18841046, -119.3882348))
        .radius(300)
        .categories(vec![String::from("bathroom")])
        .limit(10)
        .build()
        .unwrap();
```
3. Run example + see error

**Expected behavior**
The optional data should resolve to None.
```rust
    /// Price level of the business.
    ///
    /// Value is one of $, $$, $$$ and $$$$.
    pub price: Option<PriceType>,
```

**Screenshots**
![image](https://user-images.githubusercontent.com/17330223/212620468-1c395da6-570c-4609-b531-302b00825d15.png)

Note:
This repository seems locked down, I cannot make a branch.

**Comment by goddtriffin** [comment]
Sorry for the long wait on this Issue. I'll be working on it this weekend.
